# Generated by Django 5.0.6 on 2024-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
